### ISSUE TITLE
PMD Error running Sonar

### ISSUE THREAD

**Issue by rodrigolopes** [jborgers/PMD-jPinpoint-rules#102]
We see below message when running sonar

WARNING: Exception applying rule AvoidUnnecessaryStringBuilderCreation on file file:/Users/jeroen/IdeaProjects/tci-aut/src/main/java/com/rabobank/tci/rest/authorisation/AuthRest.java, continuing with next rule
java.lang.RuntimeException: 

This is the source code:
(excluded package and imports)

`
public class AuthRest extends AbstractRest {

    private static final Logger LOGGER = LoggerFactory.getLogger(AuthRest.class);
    private static final String HMAC_SHA_256 = "HmacSHA256";

    @Autowired
    private AuthorisationRest authorisationRest;

    @Value("${environment.prefix}")
    private String environmentPrefix;

    @Value("${eventhub.base.url.format}")
    private String eventhubBaseUrlFormat;

    @Value("${tci.eventhub.name}")
    private String eventhubKeyname;

    @Value("${tci.eventhub.value}")
    private String eventhubKeyvalue;

    @Value("${tci.auth.url}")
    private String tciAuthUrl;

    public void loginAs(final String userName) {
        LOGGER.info("connecting as user: {}", userName);
        final Response loginResponse = given().get(tciAuthUrl + userName);

        final String auth_token = loginResponse.getBody().jsonPath().get(JWT);
        cacheServiceProvider.getCache().setJwtToken(auth_token);
        LOGGER.info("retrieved token: {}", auth_token);

        final String response = authorisationRest.getCurrentUserDetails();
        cacheServiceProvider.getCache().setJwtToken(response);
        LOGGER.info("expanded token with rights");
    }

    public void generateSasToken() {
        final String resourceUri = String.format(eventhubBaseUrlFormat, environmentPrefix);

        final long epoch = System.currentTimeMillis() / 1000L;
        final int week = 60 * 60 * 24 * 7;
        final String expiry = Long.toString(epoch + week);

        final String stringToSign = urlEncode(resourceUri) + "\n" + expiry;
        final String signature = getHMAC256(eventhubKeyvalue, stringToSign);

        final StringBuilder sasToken = new StringBuilder();
        sasToken.append("SharedAccessSignature sr=");
        sasToken.append(urlEncode(resourceUri));
        sasToken.append("&sig=");
        sasToken.append(urlEncode(signature));
        sasToken.append("&se=");
        sasToken.append(expiry);
        sasToken.append("&skn=");
        sasToken.append(eventhubKeyname);
        cacheServiceProvider.getCache().setSasToken(sasToken.toString());
    }

    private static String urlEncode(final String text) {
        return new String(URLCodec.encodeUrl(null, text.getBytes()), Charsets.UTF_8);
    }

    private static String getHMAC256(final String key, final String input) {
        Mac sha256HMAC = null;
        try {
            sha256HMAC = Mac.getInstance(HMAC_SHA_256);
            final SecretKeySpec secretKey = new SecretKeySpec(key.getBytes(), HMAC_SHA_256);
            sha256HMAC.init(secretKey);
            final Base64.Encoder encoder = Base64.getEncoder();

            return new String(encoder.encode(sha256HMAC.doFinal(input.getBytes())));

        } catch (final InvalidKeyException | NoSuchAlgorithmException | IllegalStateException e) {
            LOGGER.info(e.getMessage());
            final String message = "getHMAC256: " + e.getClass();
            throw new IllegalStateException(message);
        }
    }
}`

**Comment by jborgers** [comment]
More complete error message:
WARNING: Exception applying rule AvoidUnnecessaryStringBuilderCreation on file file:/Users/jeroen/IdeaProjects/tci-aut/src/main/java/com/rabobank/tci/rest/authorisation/AuthRest.java, continuing with next rule
java.lang.RuntimeException: 
(: append used in one chained statement on allocated StringBuilder and with chained toString :)
//MethodDeclaration//Block//AllocationExpression/ClassOrInterfaceType[@Image="StringBuilder" or @Image = "StringBuffer"]
/../../../PrimarySuffix[@Image = "toString"]/../PrimarySuffix[@Image = "append"][1] (: only report first append in chain :)
|
(: or :)
(: append on builder var, where var is allocated as builder :)
//MethodDeclaration//Block//PrimaryPrefix/Name[ends-with(@Image, '.append') and starts-with(@Image,
ancestor::Block//AllocationExpression/ClassOrInterfaceType[@Image="StringBuilder" or @Image = "StringBuffer"]
/ancestor::VariableDeclarator/VariableDeclaratorId/@Name)
and
(
(: and either 1. toString is called in a chain after append :)
../../PrimarySuffix[@Image = 'toString'] or
(: or 2. toString is called on the var in same block :)
substring-before(@Image, '.') = substring-before(ancestor::Block//PrimaryPrefix/Name[ends-with(@Image, '.toString')]/@Image, '.'))
(: and not append on var used in inner block like a ForStatement :)
and not(ancestor::Block//Block//PrimaryPrefix/Name[ends-with(@Image, '.append')])
(: and var not passed as argument to method :)
and not(substring-before(@Image, '.') = ancestor::Block//Statement//PrimarySuffix/Arguments//Name/@Image)
]
	          had problem: A sequence of more than one item is not allowed as the first argument of substring-before() ("Long.toString", "sasToken.toString") 
	at net.sourceforge.pmd.lang.rule.xpath.SaxonXPathRuleQuery.evaluate(SaxonXPathRuleQuery.java:145)
	at net.sourceforge.pmd.lang.rule.XPathRule.evaluate(XPathRule.java:176)
[...]
