### ISSUE TITLE
Fix Request: AvoidURLEncoder says URLEncoder.encode(String, Charset) is slow on IBM JVM 8, but wasn't available in that version of Java

### ISSUE THREAD

**Issue by FrenkelS** [jborgers/PMD-jPinpoint-rules#108]
The statement ```java.net.URLEncoder.encode("", java.nio.charset.StandardCharsets.UTF_8)``` triggers the warning "java.net.URLEncoder.encode is used. Slow on IBM JVM, at least up to version 8.".
While ```URLEncoder.encode(String, String)``` is available since Java 1.4, ```URLEncoder.encode(String, Charset)``` was introduced in Java 10. So it's impossible to be slow on IBM JVM 8.

**Comment by jborgers** [comment]
Fixed in company specific rule set
