### ISSUE TITLE
Fix request: AvoidMutableLists has a false-positive using in an Entity class with linked List

### ISSUE THREAD

**Issue by MarkvanOsch** [jborgers/PMD-jPinpoint-rules#129]
This is a false-positive sonar issue: ("pmd:AvoidMutableLists"). 

As per description:
A list which is unnecessarily mutable may accidentally be added to and cause a memory leak.             
Solution: 
Make it impossible to modify the list after initialization: use Java 9 List.of, Collections.unmodifiableList or Guava ImmutableList.   

Using stream() with map new object and add also makes list immutable.

Example code (snippets, not complete code:

```
public class Item {

    private final List<String> properties = new ArrayList<>();

    public Item(List<String> properties) {
        properties.stream()
            .map(String::new)
            .forEach(this.properties::add);
    }
}
```

**Comment by jborgers** [comment]
Needs rewrite from @MarkvanOsch, issue is different

**Comment by jborgers** [comment]
For JPA @Entity, Hibernate manages magically the mapping to the database tables, it will modify lists and sets by bytecode injection. So this is not visible in the code, other than the annotations: @OneToMany and @ManyToMany.
So, fox should be to exclude fields that are annotated that way.

**Comment by MarkvanOsch** [comment]
These are the possible annotations that I see for a List in an Entity.

import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

@OneToMany
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
@ManyToMany
@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
private List<String> properties;
private final List<String> properties = new ArrayList<>();
