### ISSUE TITLE
Rule Request: Split InconsistentEqualsAndHashCode into multiple rules

### ISSUE THREAD

**Issue by FrenkelS** [jborgers/PMD-jPinpoint-rules#131]
InconsistentEqualsAndHashCode is a Blocker that says every field that is used in `equals` must also be used in `hashCode`. This is a bit too strict when you look at the contract of `hashCode`. 

Differentiate between to cases:
case 1: `hashCode` uses field not in `equals`: prio Blocker
case 2: `equals` uses a field not in `hashCode`: lower prio (Critical or Major)

and maybe, case 3: The extreme case in which `hashCode` doesn't use any of the fields used in `equals`, in other words, it returns the same constant for every instance. a prio lower than Blocker.

**Comment by jborgers** [comment]
New rule added: MissingFieldInHashCode with a Critical severity instead of Blocking
