### ISSUE TITLE
Fix Request - pmd:InconsistentEqualsAndHashCode - false positive

### ISSUE THREAD

**Issue by marius-cornescu** [jborgers/PMD-jPinpoint-rules#153]
Violation is triggered, but I see no issue:

`

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        MyClass that = (MyClass) o;
        return header.equals(that.header) && trailer.equals(that.trailer) && valuezz.equals(that.valuezz);
    }

    @Override
    public int hashCode() {
        return Objects.hash(header, trailer, valuezz);
    }
`

**Comment by marius-cornescu** [comment]
For all 3 members we get "Equals and hashCode are not based on the same fields or use inconsistent conversion."

**Comment by jborgers** [comment]
If you add NullPointerException protection by Objects.equals or with an if-clause, then it is a tested case and it works as expected.
