### ISSUE TITLE
AvoidApacheCommonsFileItemNonStreaming: improve tests 

### ISSUE THREAD

**Issue by jborgers** [jborgers/PMD-jPinpoint-rules#24]
separate test-code cases: get, getString, harmless; add testcase with fully qualified classname (no import)

**Comment by jborgers** [comment]
Also of note, the test mentions JPCC-19, but I don’t know that that is, and I searched for it online to no avail… maybe provide a link instead?
--> when a github issue, we will provide a link

**Comment by Jangor67** [comment]
Fixed
