### ISSUE TITLE
incorrect rule encountered: Unused assignments should be removed

### ISSUE THREAD

**Issue by tazzer512** [jborgers/PMD-jPinpoint-rules#249]
I am getting sonar complaints abouts variables not being used, even though they are used in the next method calls, for example:

Remove this useless assignment to local variable "debetAccount".

rule: Unused assignments should be removed java:S1854

 private void doSometing(Order order) {
        Data debetAccount = service.getData(order.getAccount()).get(0);

// sonar: Remove this useless assignment to local variable "debetAccount".
        enrich(debetAccount);
    }

**Comment by jborgers** [comment]
Turns out to be a Sonar internal rule which results in many false-positives. To be switched off.

I was confused with pmd:AvoidUnusedAssignments, which is working correctly (so far).
