### ISSUE TITLE
how to integrate into sonar-pmd-plugin? 

### ISSUE THREAD

**Issue by ruojingO** [jborgers/PMD-jPinpoint-rules#265]
very thanks your ruleset , now we use sonarqube the latest 10.x version, sonar-pmd-plugin 3.4.1-snapshot, can you share know the  rapid approach to intergrate the ruleset into plugin ?

**Comment by jborgers** [comment]
Did you try [sonar-pmd-custom](https://github.com/jborgers/sonar-pmd-custom)?
Not sure it supports Sonar 10.x

**Comment by ruojingO** [comment]
> Did you try [sonar-pmd-custom](https://github.com/jborgers/sonar-pmd-custom)? Not sure it supports Sonar 10.x

very thansgiving ,use this custom plugin ,is ok .tested pass in sonar10.0.x  .. :)

**Comment by jborgers** [comment]
You are welcome. Good to know it works.
