### ISSUE TITLE
Request for rule to check CDI.current usage to prevent memory leak

### ISSUE THREAD

**Issue by zubcevic** [jborgers/PMD-jPinpoint-rules#28]
Can you create a rule to detect a potential memory leak when CDI.current().select is used?:

The following code will have a memory leak when the finally destroy is not used.

See more info: https://blog.akquinet.de/2017/01/04/dont-get-trapped-into-a-memory-leak-using-cdi-instance-injection/

MyClass myObject= CDI.current().select(MyClass.class).get();
        try {
        ....//do stuff
        } finally {
            CDI.current().destroy(myObject);
        }

**Comment by jborgers** [comment]
Rule created with tests. To be verified by requestor.

**Comment by zubcevic** [comment]
looks fine, but hard to see from the file contents alone. Do you have a sample project that you use to test the outcome. Both positive and negative?

**Comment by jborgers** [comment]
Unit tests are included, based on the code you posted. Can you verify this on your project code from before your fix and after? So, Run PMD-plugin with the jpinpoint-rules.xml provided from this repo.

**Comment by zubcevic** [comment]
verified with maven pmd plugin at level 2
and the ruleset from this commit
