### ISSUE TITLE
Request for false-positive fix: Exclude class annotated with @ConfigurationProperties from thread-safety rules

### ISSUE THREAD

**Issue by Stijn123456** [jborgers/PMD-jPinpoint-rules#29]
When using @ConfigurationProperties(prefix="<your prefix>") to inject configuration properties into a Spring-Boot application, Sonar returns the pmd:AvoidUnguardedAssignmentToNonFinalFieldsInSharedObjects warning. Since the setters of this class are only called once, this kind of thread-safety rules are not necessary in these cases and classes with this annotation can be excepted from this rule. 
Kind regards, 
Stijn Schmeink

**Comment by jborgers** [comment]
@SchmeinkS can you validate if this fixes your issue? Use jpinpoint-rules from this repo to test on your source code.

**Comment by jborgers** [comment]
fixed
