### ISSUE TITLE
Request for fix: False positive in pmd:MinimizeAttributesInSession

### ISSUE THREAD

**Issue by WijnandsM** [jborgers/PMD-jPinpoint-rules#32]
When calling method setAttribute on a class which is not an HttpSession, pmd:MinimizeAttributesInSession is still triggered resulting in a false positive. Possible cause is a literal scan for the method setAttribute without checking if it is actually called on an HttpSession.

**Comment by jborgers** [comment]
Extra test case:
 class Test5_Ok {
	public void setAttribute(final String sessionAttributeName,
							 final Object object) {
		getOther().setAttribute(sessionAttributeName, object); // good
	}

	public Object getAttribute(final String sessionAttributeName) {
		return getOther().getAttribute(sessionAttributeName);
	}

	Other getOther() {
		return new Other();
	}
}
 class Other {
	void setAttribute(String n, Object o) {}
	Object getAttribute(String n) {}
}

**Comment by jborgers** [comment]
Check for types defined in the class: 
javax.portlet.PortletSession
javax.servlet.http.HttpSession

**Comment by jborgers** [comment]
fixed

**Comment by jborgers** [comment]
Verified in bc application now correctly reports violations on HttpSession::setAttribute usage while it did not before.
