### ISSUE TITLE
Request for fix: False positive MDCPutWithoutRemove

### ISSUE THREAD

**Issue by singaravadivelu** [jborgers/PMD-jPinpoint-rules#51]
In the Interceptor, "**preHandle**" method has the **mdc.put** and in the method "**afterCompletion**" did **mdc.clear()**.
But **PMD** doesn't **recognize** this **mdc.clear()**. It complains.

**Comment by jborgers** [comment]
Holds for classes implementing Spring WebRequestInterceptor. 
If MDC.clear() is called in afterCompletion, it is not a violation.
