### ISSUE TITLE
Request for fix: False positive MDCPutWithoutRemove 

### ISSUE THREAD

**Issue by SingaravadiveluBalasubramanian** [jborgers/PMD-jPinpoint-rules#67]
In the Interceptor, "preHandle" method has the mdc.put and in the method "afterCompletion" did mdc.remove().
But PMD doesn't recognize this mdc.remove() and It complains.

**example below:**

       @Override
    public void preHandle(WebRequest webRequest) throws Exception {
        MDC.put("key1", "value1");
    }

    @Override
    public void afterCompletion(WebRequest webRequest, Exception e) throws Exception {
        MDC.remove("key1");
    }

**Comment by jborgers** [comment]
Fixed
