### ISSUE TITLE
Request for new rule: AvoidJAXBUtil

### ISSUE THREAD

**Issue by stokpop** [jborgers/PMD-jPinpoint-rules#73]
IUOXAR10
Observation: javax.xml.bind.JAXB utility class is used for marshalling or unmarshalling

Problem: the JAXB class is not optimised for performance and multi-threaded usage. For instance, if multiple types are marshalled, with multiple JAXBContext's, the JAXBContext's are not reused. When URLs are supplied, the context is fetched outside of http connection pools with proper timeout properties and connection sharing. No validation is performed (if you need that, better skip validation when you can for better performance).

Solution: use JAXB API directly for marshalling and unmarshalling to gain all the performance benefits as described in IUOXAR04 and IUOXAR06

Example:

```java
public class XMLConversion {
    public <T> T myUnmarshal(final Source response, final Class<T> clazz) {
            return JAXB.unmarshal(response, clazz); // violation
    }
    public void myMarshal(final Object response, StringWriter stringWriter) {
        JAXB.marshal(response, stringWriter); // violation
    }
}
```

See pull request: https://github.com/jborgers/PMD-jPinpoint-rules/pull/72

**Comment by jborgers** [comment]
done
