### ISSUE TITLE
Request for fix: false positive in AvoidImproperAnnotationCombinations

### ISSUE THREAD

**Issue by Ez2** [jborgers/PMD-jPinpoint-rules#86]
**This rules states:**

_Improper combination of annotations. Problem: these annotations are not meant to be combined and may cause unexpected and unwanted behavior. Solution: remove the inappropriate annotation. Don't combine 2+ of [`@Component`, `@Service`, `@Configuration`, `@Controller`, `@Repository`, `@Entity`, `@Aspect`] (Spring/JPA/AspectJ) Don't combine [`@Data` with `@Value`] and [`@Data` or `@Value`] with any of [`@ToString`, `@EqualsHashCode`, `@Getter`, `@Setter`, `@RequiredArgsConstructor`] (Lombok) (jpinpoint-rules)_

This is all right for the Lombok annotations and the Spring annotations. But I have a problem with disallowing @Component with @Aspect. The current spring documentation states:
 

**Autodetecting aspects through component scanning**
 
You can register aspect classes as regular beans in your Spring XML configuration or autodetect them through classpath scanning — the same as any other Spring-managed bean. However, note that the `@Aspect` annotation is not sufficient for autodetection in the classpath. For that purpose, you need to add a separate `@Component` annotation (or, alternatively, a custom stereotype annotation that qualifies, as per the rules of Spring’s component scanner).
 
https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/core.html#aop-at-aspectj
 
So implementing this rule AvoidImproperAnnotationCombinations would make our code fail. For that reason, we would like to have this change reverted.

**Comment by jborgers** [comment]
Are combinations of  @Aspect with any of [@Service, @Configuration, @Repository, @Controller, @Entity] valid as well?

**Comment by Ez2** [comment]
I think they are valid combinations, because the documentation states "or, alternatively, a custom stereotype annotation that qualifies, as per the rules of Spring’s component scanner", and basically @service, @configuration, @repository and @controller are all picked up by the component scanner as @components. This is not the case for @entity, by the way, because that is not a spring annotation.

**Comment by jborgers** [comment]
Right, good point. However, if I understand correctly, to autodetect aspects, the way to achieve this is to add an annotation like @Component to let the component scanner pick it up. For me this smells like a workaround, a trick. It is not that the Aspect annotated class is classified as a component in an architectural layer. I also find it confusing to mix the singleton characteristics with a cross-cutting concern. What if you use synchronized on a method in the Aspect? What is the implicit lock? How about lock contention?

If I see the definition:
@Component is a generic stereotype for any Spring-managed component
@Service annotates classes at the service layer
@Repository annotates classes at the persistence layer, which will act as a database repository

Then I think although it is allowed, it doesn't make sense to combine @Aspect with any other of the mentioned annotations than @Component. In fact, it is probably wrong, or at least very confusing. 
What do you think?

**Comment by Ez2** [comment]
Those are some heavy questions 😄 

To temper expectations, I'm definitely not an expert in using aspects. We currently only have one in our projects, the PerformanceLogAspect, which is a Spring bean and wraps around certain annotated methods to record how long each takes and logs this. I have no idea about how locking works in an aspect, because I've never explicitly tinkered with that, nor do I intend to, because when using Spring, I have never needed to do my own locking. Spring takes care of that. Perhaps I'll takes this as a subject for a Brainbit one day. Be aware, by the way, that there are multiple ways to use the @Aspect annotation. You can use the Spring proxy based approach, or use the full fledged AspectJ implementation. Both probably have their own quirks. 

As to the more philosophical questions you pose, the @Component annotation on a class simply means we intend that class to be instantiated as a (singleton) Spring bean. It has nothing to do with the term components meant in the architectural sense, it's just how Spring names things. By the way, I have no problem with singletons used for cross cutting concerns, as long as Spring does the required locking, or the shared object is either immutable or threadsafe. 

But, I suppose it's okay with me to have a rule that we don't want to have a class that has an @Aspect and also @Repository or @Service. I did find an example somewhere of @Aspect being used with @Configuration in an older version of Spring, so it might be wise not to forbid that. 

Does this answer your questions sufficiently?

**Comment by jborgers** [comment]
Fixed
