### ISSUE TITLE
Rule request: HttpClientBuilderWithoutPoolSize

### ISSUE THREAD

**Issue by stokpop** [jborgers/PMD-jPinpoint-rules#91]
In almost all cases we encounter, the default connection timeouts and connection pool sizes are not what is needed for Apache HttpClient.

Also, when using the defaults, better make it explicit that the chosen timeouts and size are consciously chosen.

For this example:

```java
        return HttpClients.custom()
                          .setSSLSocketFactory(sslSocketFactory)
                          .setConnectionManager(poolingHttpClientConnectionManager)
                          .build();
```

add size (default is 2 per route and 20 total) explicitly, appropriate for your use case:

```java
        return HttpClients.custom()
                    .setSSLSocketFactory(sslSocketFactory)
                    .setConnectionManager(poolingHttpClientConnectionManager)
                    .setMaxConnTotal(10)
                    .setMaxConnPerRoute(10)
                    .build();
```

When using one HttpClient for one route, it makes most sense to make total and per route equal.

**Comment by jborgers** [comment]
added
