### ISSUE TITLE
'Non-reproducable' false positive on AvoidUnguardedMutableInheritedFieldsInSharedObjects because of solved deprecations

### ISSUE THREAD

**Issue by jborgers** [jborgers/PMD-jPinpoint-rules#94]
AvoidUnguardedMutableInheritedFieldsInSharedObjects matches on non-fields, a false positive.
Turns out it only happens with older version of the PMD-plugin, the newest one for IntelliJ 2019. 
Upgrade to newest IntelliJ and PMD-plugin solves this issue.

And also in the VSTS pipeline using the maven-pmd-plugin version 3.12.0. Unfortunately, upgrading to 3.13 (early 2020) does not help. It seems this plugin doesn't use a new enough version of PMD.

It seems that solving the deprecation warnings in the XPath expressions when running pmd (6.27) of the rules causes this. Strange that only this rule seems affected and only one person reached out.

**Comment by jborgers** [comment]
It concerns the two occurrences of VariableDeclaratorId/@Name in the xpath expression. 
The deprecated version is: VariableDeclaratorId/@Image.
Change back to deprecated version.

**Comment by sivagnanavelu** [comment]
I faced the issue with intelliJ version **2019.2** PMD plugin. As per your suggestion I have upgraded to newer version of IntelliJ.   after upgrading the intelliJ version Ultimate **2020.2** the issue solved.  

In pipeline It was failed when using the maven-pmd-plugin version 3.12.0.  After upgrading to 3.13.0 this issue resolved.

Please note:  I am using the latest ruleset (jpinpoint-rules.xml)

Thank you,
Siva

**Comment by jborgers** [comment]
maven-pmd-plugin version 3.13.0 uses an old version of pmd. version 3.14.0 seems to be released, however is not available in maven central, yet.

**Comment by adangel** [comment]
The release process is still ongoing.
If you only want to use a new PMD version than the default, then you can update it already: https://maven.apache.org/plugins/maven-pmd-plugin/examples/upgrading-PMD-at-runtime.html

**Comment by jborgers** [comment]
Thanks Andreas! This seems to work well.

**Comment by adangel** [comment]
m-pmd-p 3.14.0 is now also available.

**Comment by jborgers** [comment]
Even better. Great. This is solved.
